"""test2

Revision ID: 02_675a2fb1ef50
Revises: 01_b11f147413e8
Create Date: 2024-04-28 07:13:25.404952

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02_675a2fb1ef50"
down_revision: Union[str, None] = "01_b11f147413e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_login_key", "user", type_="unique")
    op.create_index("idx_lower_login", "user", [sa.text("lower(login)")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_lower_login", table_name="user")
    op.create_unique_constraint("user_login_key", "user", ["login"])
    # ### end Alembic commands ###
